cdの設定
takumaosada/ostk_profile_site pull request #8
Opened 2019-09-29 16:01 UTC by nisshii0313

とりあえず雛形を書いたお

2019-09-29 16:03 UTC, nisshii0313 commented on .github/workflows/deploy.yml
> +        npm run generate
ここら辺はpackage.jsonのscriptsの設定次第だから要変更な気がする

2019-09-30 02:05 UTC, ostk0069 requested changes

2019-09-30 02:05 UTC, takumaosada commented on .github/workflows/deploy.yml
> +        npm run generate
```
npm install
npm run dev
```
に変更すればいけると思われ

2019-09-30 02:05 UTC, takumaosada commented on .github/workflows/deploy.yml
> +        npm run generate
`npm run generate`はnuxt.jsの時のコマンド

2019-09-30 04:00 UTC, ostk0069 approved these changes
LGTM 
<img src="http://pbs.twimg.com/media/CmnM2X0UcAACo7K.jpg" alt="" title="">

2019-09-30 04:01 UTC, merged